### ISSUE TITLE
blacklist is not appropriate at all

### ISSUE THREAD

**Issue by albjeremias** [b3yond/ticketfrei#31]
hei, can the term "blacklist" stop being used by computer geeks? It's such a racist term... it can be so easily replaced with "allowed list" "deny list" or... "blocklist" and "safelist" 

thanks! :)

**Comment by b3yond** [comment]
sorry, I wasn't aware. will change it.

**Comment by b3yond** [comment]
so, now it should be fixed on the multi-deployment branch, which is our development branch :) it will move to production environments soon.
